x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: ${FLUENT_BIT_ADDRESS}:24224

services:
  gateway:
    build:
      context: https://github.com/DanijelRadakovic/Servers-Front.git#v1.1.1
      target: execute
      args:
        API_URL: "  apiUrl: 'http://localhost:8000/servers/api/server'"
    image: danijelradakovic/servers-front:${FRONT_VERSION:-latest}
    restart: on-failure
    networks:
      - servers
      - monitoring
    ports:
      - "8000:8000"
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf
      - ./front/api_gateway.conf:/etc/nginx/api_gateway.conf
    logging: *fluent-bit
    depends_on:
      - servers

  servers:
    build: 
      context: ./
      dockerfile: Dockerfile
      target: ${TARGET:-appWebServerRuntime}
    image: danijelradakovic/servers:${VERSION:-latest}
    restart: on-failure
    networks:
      - servers
      - monitoring
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DOMAIN: ${DATABASE_DOMAIN}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      JAEGER_DOMAIN: ${JAEGER_DOMAIN}
    logging: *fluent-bit
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:${POSTGRES_VERSION-13}
    restart: always
    networks:
      - servers
      - monitoring
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      retries: 3
      interval: 5s
      timeout: 5s
    volumes:
      - database-data:/var/lib/postgresql/data
    logging: *fluent-bit

  pgadmin:
    image: dpage/pgadmin4:5.3
    networks:
      - servers
      - monitoring
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ROOT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ROOT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PUBLISHED_PORT-8081}:80"
    logging: *fluent-bit
    depends_on:
      - database

volumes:
  database-data:
    name: server-database
  pgadmin:
    name: pgadmin

networks:
  servers:
    name: servers
    driver: bridge
  monitoring:
    external: true
